language: java
deploy:
  on:
    branch: main
  skip_cleanup: true
  provider: heroku
  app: myapp-ainhoahdez
  api_key:
    secure: BYkPEHUh83O5HsWxjlKN2XXiuKdb/oJgRI0NYPcfrsgCY0UVRxByyepoCHbkrxttB06kuZ0yAN15DTPF4Av37GkhO2joJcexPoIuMET8fvueH/ijYa8+NbYNq1n5KE1BTO6icUkyM3uTkmzpigQ+2kFeK+vJIkVKu0CTF4OsE2JzF1ciqnS/vbEdS2sXJMo8PQMUnERN3V56I7Bj6uYpOTgt5+UTo6rsPTCDTVCpmUvUJkuuQqQdBCVv4CNp16yA8Jsu9EMveMrNtOvOaLReKYbgcMku43/vhavbn7MINQcjW7PyOnpzUDI3xNmbIsB7HxjlE3LgiD/JBup2n9XER4iM+ddPXTYtO/azA9Iv28lQ4sOSowPf6V4e+wu2BIizw8ts1wTtgWBEW6onSCPnGXRYnqqdT2aGUP42wEfT8knNG4OTMer9G25xQhHDU2ZOXRtTtm38sWdbX0aXF2w4potEc8mmsDlbhYrJtcnF2qu7aFfkofQzMSoQEyVKgiG9AW+1beBPlNbPtOj5Vai1tTizy5hsxbRSaouR/RzKlGeILGGKIH0+pBLS7ErR/2SDKovFkr4qZSNUfi3wGPwFNERDotayQEP5341L4nmcQwjyNNCYAjEGn0Xhpe5hL2IY6t93yRAIdzk08/eJjMuC0qcK6U10Cjp60s5Az4c3Caw=
